apiVersion: v1
kind: Service
metadata:
  name: pathan-nginx-service
spec:
  type: ClusterIP                 # Internal cluster IP network type
  selector:
    app: pathan-web               # Matches the labels on your deployment pods
  ports:
  - protocol: TCP
    port: 80                      # Service port
    targetPort: 80                # Pod container port
    